---

version: "3.8"

services:
  app:
    build: .
    command: http://solr:8983

  solr:
    image: solr:8.11.2
    entrypoint:
      - bash
      - -c
      - -e
      - > 
        precreate-core test-core1 /opt/solr/server/solr/configsets/_default;
        precreate-core test-core2 /opt/solr/server/solr/configsets/sample_techproducts_configs;
        solr-foreground
