name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests the image using docker-compose with a fresh Solr server
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run the test script
        run: bash test.sh

      - name: Stop containers
        if: always()
        run: docker-compose down -v
